# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a660d92102f0f0ae3990478121a64e596bf98bf98a70f5f8a87e5fef427dc5482fbd2ba8953a9c3d22fa3e4dbd3237eac87cfb29afc66fc4378ed1a61fb55310

test:
  secret_key_base: 3fc53bad07ac8f2a1c1f60e3270e4a944ff0f211ec8ee2b0e98bdeaecf9b7086b3e2b60b028e62be70a50b741fdb3ffd33af67fd50c3ebae21caee8a0a57b32c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
